services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hiresync-app
    env_file:
      - ./src/main/resources/.env
    ports:
      - "${PORT:-8080}:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - hiresync-network
    # Environment variables defined here will override those in the .env file
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - SPRING_PROFILES_ACTIVE=prod
      - JPA_DDL_AUTO=validate

  postgres:
    extends:
      file: docker-compose.yaml
      service: postgres

networks:
  hiresync-network:
    driver: bridge

volumes:
  postgres-data: 