services:
  postgres:
    image: postgres:16-alpine
    container_name: hiresync-postgres
    ports:
      - "${DB_PORT:-5544}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-hiresync_db}
      - POSTGRES_USER=${DB_USERNAME:-hiresync_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-hiresync_password}
    networks:
      - hiresync-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-hiresync_user} -d ${DB_NAME:-hiresync_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  hiresync-network:
    driver: bridge

volumes:
  postgres-data: