services:
  postgres:
    image: postgres:16-alpine
    container_name: hiresync-postgres
    ports:
      - "5544:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hiresync_db
      - POSTGRES_USER=hiresync_user
      - POSTGRES_PASSWORD=hiresync_password
    networks:
      - hiresync-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hiresync_user -d hiresync_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9010:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - hiresync-network

networks:
  hiresync-network:
    driver: bridge

volumes:
  postgres-data:
  minio-data: