server:
  port: ${PORT:8080}
  tomcat:
    max-threads: 300
    min-spare-threads: 30
    connection-timeout: 20000
    max-connections: 15000

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
  datasource:
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:20}
      minimum-idle: ${DB_MIN_IDLE:10}

logging:
  level:
    root: ERROR
    com.zbib.hiresync: WARN
    org.springframework.web: ERROR
    org.hibernate: ERROR

# Security headers
server.servlet.session:
  cookie:
    secure: true
    http-only: true
    same-site: strict

# CORS configuration
hiresync:
  cors:
    allowed-origins: https://hiresync.example.com
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    max-age: 3600 