# Configuration for tests with H2 in-memory database
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

# Test-specific logging
logging:
  level:
    root: WARN
    com.zbib.hiresync: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.test: INFO

# Enable API docs for testing
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

# Test environment specific JWT configuration
jwt:
  secret: test-secret-key-with-minimum-length-of-32-characters
  issuer: hiresync-test
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds
  
# Test environment specific features
hiresync:
  features:
    debug-mode: true
