# Production environment configuration
spring:
  datasource:
    # Use the POSTGRES environment variables from Render
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_IDLE:2}
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Production logging configuration
logging:
  config: classpath:log4j2.xml
  level:
    root: WARN
    com.zbib.hiresync: WARN
    org.hibernate.SQL: ERROR
    org.springframework.web: WARN

# Disable documentation UI in production
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# Production environment specific JWT configuration
jwt:
  issuer: hiresync-prod

# Production environment specific features
hiresync:
  features:
    debug-mode: false
    enable-email-notifications: true
