# Local environment configuration
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hiresync}
    username: ${DB_USER:hiresync}
    password: ${DB_PASSWORD:hiresync}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      pool-name: HireSyncHikariPool
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources
      exclude: static/**,public/**
    livereload:
      enabled: true

# Logging configuration
logging:
  level:
    root: INFO
    com.zbib.hiresync: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.zbib.hiresync.logging: DEBUG
    org.springframework.aop: WARN

# API Documentation - override specific settings
springdoc:
  swagger-ui:
    operationsSorter: method
    filter: true
    display-request-duration: true
  cache:
    disabled: true

# Local environment features
hiresync:
  features:
    debug-mode: true
    enable-email-notifications: false
