spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never

logging:
  level:
    root: INFO
    com.zbib.hiresync: DEBUG
