# Configuration for tests with PostgreSQL database
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/testdb}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Test-specific logging
logging:
  level:
    root: WARN
    com.zbib.hiresync: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.test: INFO

# Disable API docs for testing
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

# Test environment specific JWT configuration
jwt:
  secret: test-secret-key-with-minimum-length-of-32-characters
  issuer: hiresync-test
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds
  
# Test environment specific features
hiresync:
  features:
    debug-mode: true
