# Production environment configuration
spring:
  datasource:
    # In production, database connection should be provided by environment variables
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_IDLE:2}
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Production logging configuration
logging:
  level:
    root: INFO
    com.zbib.hiresync: INFO
    org.hibernate.SQL: ERROR
    org.springframework.web: WARN

# Disable documentation UI in production
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# Production environment specific JWT configuration
jwt:
  issuer: hiresync-prod

# Production environment specific features
hiresync:
  features:
    debug-mode: false
    enable-email-notifications: true
