server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true

spring:
  main:
    banner-mode: off
  application:
    name: hiresync-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/hiresync}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_IDLE:5}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Security configuration
security:
  jwt:
    issuer: hiresync
    audience: hiresync-app
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000}

# Logging configuration
logging:
  config: classpath:log4j2.xml
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.zbib.hiresync: ${LOG_LEVEL_APP:INFO}
    org.hibernate.SQL: ${LOG_LEVEL_SQL:ERROR}
    org.hibernate.type.descriptor.sql: ${LOG_LEVEL_SQL_PARAMS:ERROR}

# Actuator configuration 
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: ${ACTUATOR_DETAILED_HEALTH:never}
    prometheus:
      enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# API documentation configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true
    enabled: ${SPRINGDOC_ENABLED:true}
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    enabled: ${SWAGGER_UI_ENABLED:true}
  cache:
    disabled: false
