# Production environment configuration
spring:
  datasource:
    # Support multiple environment variable patterns for database connectivity
    url: ${SPRING_DATASOURCE_URL:${JDBC_DATABASE_URL:jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:hiresync}}}
    username: ${SPRING_DATASOURCE_USERNAME:${JDBC_DATABASE_USERNAME:${POSTGRES_USER:postgres}}}
    password: ${SPRING_DATASOURCE_PASSWORD:${JDBC_DATABASE_PASSWORD:${POSTGRES_PASSWORD:postgres}}}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_IDLE:2}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Production logging configuration
logging:
  config: classpath:log4j2.xml
  level:
    root: WARN
    com.zbib.hiresync: WARN
    org.hibernate.SQL: ERROR
    org.springframework.web: WARN

# Disable documentation UI in production
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# Production environment specific JWT configuration
jwt:
  issuer: hiresync-prod

# Production environment specific features
hiresync:
  features:
    debug-mode: false
    enable-email-notifications: true
