spring:
  jpa:
    hibernate:
      ddl-auto: create-drop # for staging and setup 
    show-sql: false

server:
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false

logging:
  level:
    root: INFO
