# Base configuration shared across all environments
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: 
      - text/html
      - text/xml
      - text/plain
      - text/css
      - application/javascript
      - application/json
    min-response-size: 1024
  http2:
    enabled: true
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

spring:
  main:
    banner-mode: off
  application:
    name: hiresync-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    driver-class-name: org.postgresql.Driver
    # Updated to use consistent variable naming
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:hiresync}
    username: ${POSTGRES_USER:hiresync}
    password: ${POSTGRES_PASSWORD:hiresync}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:5}
      minimum-idle: ${DB_MIN_IDLE:2}
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
      pool-name: HireSyncHikariCP
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 25
        order_inserts: true
        order_updates: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  aop:
    auto: true
    proxy-target-class: true
  lifecycle:
    timeout-per-shutdown-phase: 30s
  task:
    execution:
      pool:
        core-size: 4
        max-size: 8
        queue-capacity: 100
        keep-alive: 60s
      thread-name-prefix: hiresync-task-

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:CHANGE_ME_IN_PRODUCTION}
  expiration: ${JWT_EXPIRATION:86400000}
  issuer: ${JWT_ISSUER:hiresync}
  audience: ${JWT_AUDIENCE:hiresync-app}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

# Security configuration
security:
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000}
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - PATCH
    allowed-headers:
      - Authorization
      - Content-Type
      - Accept
      - X-Requested-With
      - X-API-Key
    allow-credentials: true
    max-age: 3600

# Logging base configuration
logging:
  config: classpath:log4j2.xml
  level:
    root: INFO
    org.springframework: WARN
    com.zbib.hiresync: INFO
    org.hibernate.SQL: WARN
    com.zaxxer.hikari: WARN

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: ${ACTUATOR_DETAILED_HEALTH:never}
      probes:
        enabled: true
    prometheus:
      enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  server:
    port: ${MANAGEMENT_PORT:8081}
    address: 127.0.0.1

# API documentation base configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true
    enabled: ${SPRINGDOC_ENABLED:true}
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    enabled: ${SWAGGER_UI_ENABLED:true}
    disable-swagger-default-url: true
  cache:
    disabled: false
  show-actuator: true
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true

# Application Configuration
hiresync:
  features:
    enable-file-upload: ${ENABLE_FILE_UPLOAD:true}
    enable-email-notifications: ${ENABLE_EMAIL:false}
    debug-mode: ${DEBUG_MODE:false}
  logging:
    sensitive-fields:
      - password
      - token
      - secret
      - key
      - credential
      - ssn
      - socialSecurityNumber
      - creditCard
    enabled-aspects:
      - service
      - controller
      - repository
    force-debug-packages:
      - com.zbib.hiresync.auth
      - com.zbib.hiresync.security
  rate-limiting:
    enabled: true
    default-limit: 100
    default-duration: 60
