# Local environment configuration
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hiresync}
    username: ${DB_USER:hiresync}
    password: ${DB_PASSWORD:hiresync}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      pool-name: HireSyncLocalHikariCP
      connection-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update # Safer than create-drop for development to preserve data
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        generate_statistics: true # Enable for development profiling
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources
      exclude: static/**,public/**
    livereload:
      enabled: true
  h2:
    console:
      enabled: true # Enable H2 console for fallback to in-memory database
      path: /h2-console
  jackson:
    serialization:
      indent-output: true # Pretty-print JSON for easier development debugging
    deserialization:
      fail-on-unknown-properties: false # Consistent with application.yaml base config

# Documentation configuration
springdoc:
  swagger-ui:
    operationsSorter: method
    filter: true
    display-request-duration: true
  cache:
    disabled: true

# Logging configuration for local development
logging:
  level:
    root: INFO
    com.zbib.hiresync: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG

# Local environment features
hiresync:
  features:
    debug-mode: true
    enable-email-notifications: false
    enable-file-upload: true
  rate-limiting:
    enabled: false # Disabled for local development
