server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  main:
    banner-mode: off
  application:
    name: hiresync-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jpa:
    open-in-view: false

# JWT configuration
jwt:
  secret: ${JWT_SECRET:LONG_RANDOM_SECRET_THAT_IS_AT_LEAST_32_CHARACTERS_A1B2C3D4E5F6G7H8}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  config: classpath:log4j2.xml

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: never
  health:
    defaults:
      enabled: true

# SpringDoc/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operationsSorter: method
    filter: true
  show-actuator: true
