server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

spring:
  main:
    banner-mode: off
  application:
    name: hiresync-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/hiresync}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_IDLE:5}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # AOP configuration
  aop:
    auto: true
    proxy-target-class: true

# JWT Security configuration
jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-must-be-at-least-32-characters-long}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
  issuer: ${JWT_ISSUER:hiresync}
  audience: ${JWT_AUDIENCE:hiresync-app}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days in milliseconds

# Security configuration - for backwards compatibility
security:
  jwt:
    issuer: ${jwt.issuer}
    audience: ${jwt.audience}
    secret: ${jwt.secret}
    expiration: ${jwt.expiration}
    refresh-expiration: ${jwt.refresh-expiration}
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000}
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - PATCH
    allowed-headers:
      - Authorization
      - Content-Type
      - Accept
      - X-Requested-With
      - X-API-Key
    allow-credentials: true
    max-age: 3600

# Logging configuration
logging:
  config: classpath:log4j2.xml
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.zbib.hiresync: ${LOG_LEVEL_APP:INFO}
    org.hibernate.SQL: ${LOG_LEVEL_SQL:ERROR}
    org.hibernate.type.descriptor.sql: ${LOG_LEVEL_SQL_PARAMS:ERROR}
    # AOP logging settings
    com.zbib.hiresync.logging: DEBUG
    # Reduce noise from Spring AOP
    org.springframework.aop: WARN

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: ${ACTUATOR_DETAILED_HEALTH:never}
    prometheus:
      enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# API documentation configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true
    enabled: ${SPRINGDOC_ENABLED:true}
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    enabled: ${SWAGGER_UI_ENABLED:true}
  cache:
    disabled: false

# Application specific configuration
hiresync:
  app:
    name: HireSync API
    version: 1.0.0
    description: HireSync backend API for recruitment automation
  features:
    enable-email-notifications: ${ENABLE_EMAIL:false}
    enable-file-upload: ${ENABLE_FILE_UPLOAD:true}
    debug-mode: ${DEBUG_MODE:false}
  # Logging configuration
  logging:
    # Mask these fields in all logs
    sensitive-fields:
      - password
      - token
      - secret
      - key
      - credential
      - ssn
      - socialSecurityNumber
      - creditCard
    # Enable all aspects by default - can disable specific ones if needed
    enabled-aspects:
      - service
      - controller
      - repository
    # Force logging for specific packages even in production
    force-debug-packages:
      - com.zbib.hiresync.auth
      - com.zbib.hiresync.security
