# PostgreSQL database configuration for local development using Docker
spring:
  datasource:
    url: jdbc:postgresql://localhost:5544/hiresync_db
    username: hiresync_user
    password: hiresync_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Configure logging for local development
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.zbib.hiresync: DEBUG

# Enable Swagger UI for local development
springdoc:
  swagger-ui:
    enabled: true
