server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: hiresync-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hiresync}
    username: ${DB_USERNAME:hiresync}
    password: ${DB_PASSWORD:hiresync}
  profiles:
    active: ${PROFILE:local}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false

# OpenAPI/Swagger configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    disable-swagger-default-url: true
    urls:
      - url: /v3/api-docs
        name: HireSync API
  paths-to-match: /v1/**
  packages-to-scan: com.zbib.hiresync.controller
  show-actuator: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
  issuer: ${JWT_ISSUER:hiresync}
  audience: ${JWT_AUDIENCE:hiresync-app}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}
