package com.zbib.hiresync.dto.ai;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Response object from chat completions API.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ChatCompletionResponse {
    /**
     * The ID of the completion.
     */
    private String id;
    
    /**
     * The object type.
     */
    private String object;
    
    /**
     * The timestamp of the completion.
     */
    private long created;
    
    /**
     * The model used for completion.
     */
    private String model;
    
    /**
     * The choices generated by the model.
     */
    private List<Choice> choices;
    
    /**
     * Usage statistics.
     */
    private Usage usage;
    
    /**
     * Represents a single completion choice.
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Choice {
        /**
         * The index of the choice.
         */
        private int index;
        
        /**
         * The message generated by the model.
         */
        private ChatMessage message;
        
        /**
         * The reason the generation stopped.
         */
        private String finish_reason;
    }
    
    /**
     * Token usage statistics.
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Usage {
        /**
         * Number of tokens in the prompt.
         */
        private int prompt_tokens;
        
        /**
         * Number of tokens in the completion.
         */
        private int completion_tokens;
        
        /**
         * Total number of tokens used.
         */
        private int total_tokens;
    }
}
