version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hiresync-postgres
    ports:
      - "${DB_PORT:-5544}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-hiresync_db}
      - POSTGRES_USER=${DB_USERNAME:-hiresync_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-hiresync_password}
    networks:
      - hiresync-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-hiresync_user} -d ${DB_NAME:-hiresync_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # For local development with API server running outside Docker
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hiresync-app-local
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - hiresync-network
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=hiresync_db
      - DB_USERNAME=hiresync_user
      - DB_PASSWORD=hiresync_password
    volumes:
      - ./:/app/src
      - app-logs:/app/logs
    restart: unless-stopped

networks:
  hiresync-network:
    driver: bridge

volumes:
  postgres-data:
  app-logs: