version: '3.8'

# Production-specific configuration
services:
  # Application service
  app:
    image: ${REGISTRY:-ghcr.io}/${REPO_OWNER:-zbib}/${IMAGE_NAME:-hiresync}:${IMAGE_TAG:-latest}
    container_name: hiresync-app
    restart: ${APP_RESTART_POLICY:-always}
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - SPRING_DATASOURCE_URL=${JDBC_DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SERVER_PORT=${APP_PORT:-8080}
      - MANAGEMENT_SERVER_PORT=${ACTUATOR_PORT:-8081}
      - JAVA_OPTS=${JAVA_OPTS:--Xms512m -Xmx2g}
      - TZ=${TZ:-UTC}
    ports:
      - "${APP_PORT:-8080}:8080"
      - "${ACTUATOR_PORT:-8081}:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${ACTUATOR_PORT:-8081}/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - app-logs:/app/logs
    networks:
      - hiresync-network

# Configure volumes
volumes:
  app-logs:
    name: hiresync-app-logs

networks:
  hiresync-network:
    name: ${NETWORK_NAME:-hiresync-network}
    driver: bridge 
