version: '3.8'

# Production-specific overrides
services:
  # Use managed database in production
  postgres:
    image: postgres:16-alpine
    container_name: hiresync-postgres
    restart: ${DB_RESTART_POLICY:-always}
    environment:
      POSTGRES_USER: ${DB_USER:-hiresync}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-hiresync}
      POSTGRES_DB: ${DB_NAME:-hiresync}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-hiresync}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:${DB_PORT:-5432}:5432"
    networks:
      - hiresync-network

  # Production app config 
  app:
    image: ${REGISTRY:-ghcr.io}/${REPO_OWNER:-zbib}/${IMAGE_NAME:-hiresync}:${IMAGE_TAG:-latest}
    container_name: hiresync-app
    restart: ${APP_RESTART_POLICY:-always}
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME:-hiresync}
      - SPRING_DATASOURCE_USERNAME=${DB_USER:-hiresync}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-hiresync}
      - SERVER_PORT=${APP_PORT:-8080}
      - MANAGEMENT_SERVER_PORT=${ACTUATOR_PORT:-8081}
      - JAVA_OPTS=${JAVA_OPTS:--Xms512m -Xmx2g}
      - TZ=${TZ:-UTC}
    ports:
      - "${APP_PORT:-8080}:8080"
      - "${ACTUATOR_PORT:-8081}:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${ACTUATOR_PORT:-8081}/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - app-logs:/app/logs
    networks:
      - hiresync-network

# Configure volume backup
volumes:
  postgres-data:
    name: ${POSTGRES_VOLUME:-hiresync-postgres-data}
  app-logs:
    name: hiresync-app-logs

networks:
  hiresync-network:
    name: ${NETWORK_NAME:-hiresync-network}
    driver: bridge 