# Local development environment
name: hiresync-dev

services:
  # Database service
  postgres:
    image: postgres:16-alpine
    container_name: hiresync-postgres
    restart: "no"
    ports:
      - "127.0.0.1:${DB_PORT:-5433}:5432"
    volumes:
      - ${POSTGRES_VOLUME:-hiresync-postgres-data}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-hiresync}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-hiresync}
      POSTGRES_DB: ${DB_NAME:-hiresync}
      TZ: ${TZ:-UTC}
      PGTZ: ${TZ:-UTC}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-hiresync} -d ${DB_NAME:-hiresync}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    command: >
      postgres
        -c shared_buffers=256MB
        -c max_connections=200
        -c effective_cache_size=1GB
        -c work_mem=16MB
        -c maintenance_work_mem=64MB
        -c listen_addresses='*'
    networks:
      - hiresync-network
    labels:
      org.hiresync.component: "database"
      org.hiresync.environment: "development"

  # Development tools container (JDK + Maven)
  devtools:
    image: maven:3.9-eclipse-temurin-21-jammy
    container_name: hiresync-devtools
    restart: "no"
    volumes:
      - ..:/workspace
      - maven-repo:/root/.m2
      - ~/.gitconfig:/root/.gitconfig:ro
    working_dir: /workspace
    ports:
      - "127.0.0.1:8000:8000"     # Dev server port
      - "127.0.0.1:8080:8080"     # Spring Boot application
      - "127.0.0.1:5005:5005"     # Remote debugging
      - "127.0.0.1:9010:9010"     # JMX monitoring
    environment:
      # Pass all environment variables to the container
      - MAVEN_CONFIG=/root/.m2
      - JAVA_HOME=/opt/java/openjdk
      - MAVEN_OPTS=${MAVEN_OPTS:--Xmx1024m}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-local}
      - SPRING_APPLICATION_NAME=hiresync-api
      
      # Database connection from inside container
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-hiresync}
      - DB_USER=${DB_USER:-hiresync}
      - DB_PASSWORD=${DB_PASSWORD:-hiresync}
      
      # JWT Configuration - only set if available
      - JWT_SECRET=${JWT_SECRET:-}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}
      
      # Time zone
      - TZ=${TZ:-UTC}
    entrypoint: ["sh", "-c", "tail -f /dev/null"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - hiresync-network
    labels:
      org.hiresync.component: "development-tools"
      org.hiresync.environment: "development"

# Shared networks
networks:
  hiresync-network:
    name: ${NETWORK_NAME:-hiresync-network}

# Persistent volumes
volumes:
  hiresync-postgres-data:
    name: ${POSTGRES_VOLUME:-hiresync-postgres-data}
  maven-repo:
    name: ${MAVEN_REPO_VOLUME:-hiresync-maven-repo}
