name: Spring Boot CI Pipeline

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

# Permissions needed for GitHub Packages
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      # Set environment variables for scripts
      CI: true
      SPRING_PROFILES_ACTIVE: ci
      REGISTRY: ghcr.io
      IMAGE_NAME: hiresync

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Set execute permissions on scripts
      run: |
        chmod +x ./scripts/core/*.sh
        chmod +x ./scripts/utils/*.sh
        chmod +x ./hiresync

    - name: Run CI prepare script
      run: ./scripts/core/ci-prepare.sh

    - name: Run code linting
      run: ./scripts/core/lint.sh
    
    - name: Run security scan
      run: ./scripts/core/dependency-check.sh --format=XML
      continue-on-error: true
    
    - name: Run unit tests
      run: ./scripts/core/run-tests.sh --type=unit --profile=ci --no-container
      
    - name: Build application
      run: ./scripts/core/build-app.sh --skip-tests --profile=ci --no-container

    - name: Log in to GitHub Container Registry
      if: github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        # For PR, just build the image
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          ./scripts/core/ci-image-build.sh
        else
          # For push to branches, build and push
          ./scripts/core/ci-image-build.sh --push
        fi

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: spring-boot-app
        path: target/*.jar
        retention-days: 5
        