name: Spring Boot CI Pipeline

on:
  push:
    branches: [ master, dev ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/*.md'
  pull_request:
    branches: [ master, dev ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/*.md'
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false
        type: boolean

# Permissions needed for GitHub Packages and Code Scanning
permissions:
  contents: read
  packages: write
  security-events: write
  actions: read
  id-token: write

env:
  # Global environment variables
  JAVA_VERSION: '21'
  JAVA_DISTRIBUTION: 'temurin'
  MAVEN_OPTS: '-Xmx3072m -XX:+TieredCompilation -XX:TieredStopAtLevel=1'
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true'
  REGISTRY: ghcr.io
  IMAGE_NAME: hiresync
  DEFAULT_BRANCH: master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.changes.outputs.should_skip }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for accurate change detection

      - name: Check if workflow should be skipped
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            code:
              - 'src/**'
              - 'pom.xml'
              - 'settings.xml'
              - 'docker/**'
              - '.github/workflows/ci.yaml'
              - 'scripts/**'
              - 'config/**'
  
  quality:
    name: Code Quality
    needs: validate
    if: needs.validate.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set execute permissions on scripts
        run: |
          chmod +x ./scripts/core/*.sh
          chmod +x ./scripts/utils/*.sh
          chmod +x ./hiresync

      - name: Prepare CI environment
        run: ./scripts/core/ci-prepare.sh

      - name: Code linting and style check
        run: ./scripts/core/lint.sh

      - name: Run dependency vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          timeout: '10m'

      - name: Upload vulnerability scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'trivy-fs-scan'

      - name: Static code analysis
        run: ./scripts/core/dependency-check.sh --format=XML
        continue-on-error: true

  test:
    name: Tests
    needs: quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [unit, integration]
        include:
          - test-type: unit
            profile: ci
            use-container: false
          - test-type: integration
            profile: ci
            use-container: false
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-${{ matrix.test-type }}
          restore-keys: |
            ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-
            ${{ runner.os }}-m2-

      - name: Set execute permissions on scripts
        run: |
          chmod +x ./scripts/core/*.sh
          chmod +x ./scripts/utils/*.sh
          chmod +x ./hiresync

      - name: Run ${{ matrix.test-type }} tests
        run: ./scripts/core/run-tests.sh --type=${{ matrix.test-type }} --profile=${{ matrix.profile }} --no-container

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.test-type }}
          path: |
            target/surefire-reports/*.xml
            target/failsafe-reports/*.xml
          retention-days: 7

  build:
    name: Build & Package
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: maven

      - name: Set execute permissions on scripts
        run: |
          chmod +x ./scripts/core/*.sh
          chmod +x ./scripts/utils/*.sh
          chmod +x ./hiresync

      - name: Build application
        id: build
        run: ./scripts/core/build-app.sh --skip-tests --profile=ci --no-container

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.jar
          retention-days: 7
          if-no-files-found: error

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', env.DEFAULT_BRANCH) }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            SPRING_PROFILES_ACTIVE=dev
            SKIP_TESTS=true

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Scan Docker image for vulnerabilities
        if: github.event_name == 'push'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          severity: 'CRITICAL,HIGH'
          timeout: '10m'

      - name: Upload container scan results
        if: github.event_name == 'push'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-image-results.sarif'
          category: 'trivy-container-scan'

  summary:
    name: Build Summary
    if: always()
    needs: [validate, quality, test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Build Status Report
        run: |
          echo "## Spring Boot CI Pipeline Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Validation: ${{ needs.validate.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Code Quality: ${{ needs.quality.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Tests: ${{ needs.test.result }}" >> $GITHUB_STEP_SUMMARY 
          echo "- Build & Docker: ${{ needs.build.result }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Details" >> $GITHUB_STEP_SUMMARY
          echo "- Branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- Workflow ID: ${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY 