name: CI Pipeline

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  ci-pipeline:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Make Maven Executable
        run: chmod +x ./mvnw

      - name: Lint Code
        run: ./mvnw checkstyle:check

      - name: Build JAR
        run: ./mvnw clean package -DskipTests=true

      - name: Run Unit Tests
        run: ./mvnw test

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hiresync:latest -f docker/Dockerfile .

      - name: Run Docker Compose
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          cd docker
          docker compose -f docker-compose.test.yaml up -d
          docker compose -f docker-compose.test.yaml exec -T app bash -c "while ! nc -z postgres 5432; do sleep 1; done; ./mvnw verify -P ci -DskipUnitTests=true"

      - name: Shutdown Docker Compose
        run: cd docker && docker compose -f docker-compose.test.yaml down
