name: Spring Boot CI Pipeline

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Set execute permissions on scripts
      run: |
        chmod +x ./scripts/core/*.sh
        chmod +x ./scripts/utils/*.sh

    - name: Prepare CI environment
      run: ./scripts/core/ci-prepare.sh

    - name: Run tests
      run: ./scripts/core/test.sh

    - name: Build application
      run: ./scripts/core/build.sh --package --skip-tests

    - name: Build Docker image
      run: |
        docker build -t hiresync:${GITHUB_SHA::8} -f docker/Dockerfile .
        docker tag hiresync:${GITHUB_SHA::8} hiresync:latest

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: spring-boot-app
        path: target/*.jar
        retention-days: 5 