name: Dev Branch CI/CD Pipeline

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Check code style
        run: mvn checkstyle:check -Dcheckstyle.skip=false
        continue-on-error: true

      - name: Run static code analysis
        run: mvn pmd:check spotbugs:check
        continue-on-error: true

  test:
    name: Build and Test
    needs: validate
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: hiresync_test
          POSTGRES_USER: hiresync_user
          POSTGRES_PASSWORD: hiresync_password
        ports:
          - 5544:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Run unit tests
        run: mvn test
        env:
          DB_HOST: localhost
          DB_PORT: 5544
          DB_NAME: hiresync_test
          DB_USERNAME: hiresync_user
          DB_PASSWORD: hiresync_password
          SPRING_PROFILES_ACTIVE: test
          
      - name: Generate test report
        if: always()
        run: mvn surefire-report:report-only
        
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/site/
          retention-days: 7
          
      - name: Build package
        if: success()
        run: mvn package -DskipTests
        
      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
          retention-days: 1

  build-and-push:
    name: Build and Push Docker Image
    needs: test
    if: github.ref == 'refs/heads/dev' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=sha,format=short
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-render:
    name: Deploy to Render
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_DEV_SERVICE_ID }}
        run: |
          curl -X POST \
            "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json"
            
      - name: Verify Deployment
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_DEV_SERVICE_ID }}
        run: |
          echo "Waiting for deployment to start..."
          sleep 30
          
          MAX_ATTEMPTS=20
          ATTEMPT=1
          DEPLOYED=false
          
          while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
            echo "Checking deployment status (attempt $ATTEMPT/$MAX_ATTEMPTS)..."
            DEPLOY_STATUS=$(curl -s -H "Authorization: Bearer $RENDER_API_KEY" \
              "https://api.render.com/v1/services/$RENDER_SERVICE_ID" | \
              grep -o '"status":"[^"]*"' | cut -d'"' -f4)
              
            if [ "$DEPLOY_STATUS" == "live" ]; then
              DEPLOYED=true
              break
            fi
            
            echo "Deployment status: $DEPLOY_STATUS. Waiting 30 seconds..."
            sleep 30
            ATTEMPT=$((ATTEMPT+1))
          done
          
          if [ "$DEPLOYED" == "true" ]; then
            echo "Deployment successful!"
            exit 0
          else
            echo "Deployment timed out or failed."
            exit 1
          fi 