name: Dev Branch CI/CD

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'dev'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: hiresync_test
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: mvn -B clean package -DskipTests
      
      - name: Run tests
        run: mvn -B test
        env:
          SPRING_PROFILES_ACTIVE: test
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: hiresync_test
          DB_USERNAME: test_user
          DB_PASSWORD: test_password
      
      - name: Run code quality checks
        run: mvn -B verify
        
      - name: Build JAR file
        run: mvn -B package -DskipTests
        
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/*.jar
          retention-days: 1
          
  prepare-for-railway:
    name: Prepare for Railway Deployment
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: application-jar
          path: target
          
      - name: Install Railway CLI
        run: npm i -g @railway/cli
        
      - name: Set up Railway configuration
        run: echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}" >> $GITHUB_ENV
        
      - name: Verify Railway configuration
        run: railway whoami
        
      # Railway will detect push to dev branch via GitHub integration
      # This step is a placeholder, actual deployment handled by Railway
      - name: Notify Railway of successful build
        run: echo "Build successful and ready for Railway deployment" 